### ISSUE TITLE
Discrepancy between the subsln CLI and Visual Studio extension

### ISSUE THREAD

**Issue by icnocop** [ReMinoer/SubSolution#3]
Hi.

Thank you for SubSolution.

There seems to be a discrepancy between the behavior of the subsln CLI and the Visual Studio extension.

I've attached a set of files that can reproduce the issue.

[SubSolutionTest.zip](https://github.com/ReMinoer/SubSolution/files/8792774/SubSolutionTest.zip)

Steps to reproduce:
1. Download and extract `SubSolutionTest.zip` to a folder called `SubSolutionTest`
2. Open a command prompt
3. run `cd SubSolutionTest`
4. run `subsln generate Test.subsln --import-fallback --force`
5. Notice the CLI added the projects `ClassLibrary1` and `Dll1` to the generated solution file, as expected.
6. Open the generated `Test.sln` in Visual Studio.
7. Click `Preview` in the message "We detected new changes to apply to your solution after generation of your .subsln file." which appear at the top of the `Solution Explorer` window
8. Notice the Visual Studio extension wants to remove the `Dll1` project

I didn't expect the Visual Studio extension to want to remove the `Dll1` project.

Any ideas?

Thank you.

subsln 0.5.2+5debbb70b73093b9bd6ae2c0684ff2751e29980a
SubSolution (2022) 0.5.2
Visual Studio 2022 17.2.2

**Comment by ReMinoer** [comment]
Hi Rami, thank you for feedback and the test files. 😃 

First, the problem here is that SubSolution silently failed to read projects because of the invalid import paths from your other issue (#4). **Change the paths using $(SolutionDir) as suggested and Visual Studio plugin will behave the same as subsln.**

The Visual Studio plugin is also supposed to display an error message in the Solution Explorer if the initial background generation fail in any way. (https://github.com/ReMinoer/SubSolution/blob/master/Plugins/SubSolution.VisualStudio.Shared/Watchers/OutdatedSolutionWatcher.cs#L143)
**I will make sure that all generation errors show an error message instead of the preview message.**

---

More details:

For some reason, it was only fatal to the loading of the C++ and that's why only the C++ project was removed in the preview. But I think the loading problem also silently exists for the C# project.
In `subsln`, the option `--import-fallback` make it possible to read those projects despite import issues or missing/invalid MSBuild setup but without guarantee of result, especially on complex projects. That option doesn't exist in the Visual Studio plugin because the user is supposed to have a valid MSBuild setup in Visual Studio.

Also, after solving the .props import issue, you will have another import issue because of the default imports made by the C++ project. You should still be able to load the project with `--import-fallback` but you can also consider using the `-msbuild` option if you want to read projects the same way the VS plugin does.
You can replace `--import-fallback` by `--msbuild "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"` in your command line if you have a standard Visual Studio 2019 install.

For your information, `subsln` is using [Microsoft.Build.Locator](https://github.com/microsoft/MSBuildLocator) by default to get an existing MSBuild setup. But the current locator implementation only look for dotnet CLI setups by default, and not actual MSBuild executables installed by Visual Studio. So that's why subsln is able to read your C# projects but not your C++ projects without specifying a MSBuild directory path. **I will try to improve that in the future, or at least make it clear in the subsln tool usage.**

**Comment by ReMinoer** [comment]
With commit 777964e and version 0.6.0, generation errors will now show correctly a message box (on a generation after save) or an info bar (on background generation at solution opening). Error details can be see in the Visual Studio Output panel.

It would be even better to show the errors in the message box but I'm closing this issue since the extension now correctly show an error message to user.
