### ISSUE TITLE
Should CreateFolders="true" create folders starting from WorkspaceDirectory?

### ISSUE THREAD

**Issue by BlinD-HuNTeR** [ReMinoer/SubSolution#6]
At [SolutionBuilder.cs, Line 723](https://github.com/ReMinoer/SubSolution/blob/e45f3de0ac5a44f601bffdba8240134f4e41fe5c/Sources/SubSolution.Builders/SolutionBuilder.cs#L723), it computes the folders to be created as a relative path from the **solution directory**. 

If any project is not inside the solution folder or any of its subfolders, it will cause some ".." folders to be created in the solution structure. Is that how it's supposed to be?

Apparently changing that line to `_fileSystem.GetParentDirectoryPath(workspaceRelativeFilePath)` changes this behavior with no side effects.

P.S.: Sorry if I'm bothering you, perhaps I should just fork the project.

**Comment by ReMinoer** [comment]
Hi !
No problem, actually I'm pretty happy someone is interested by SubSolution. ^^
Open as many issues as you want and feel free to send pull request from a fork if you are confident enough to fix things by yourself.

About that behaviour, I think you are right: it would make more sense to use the workspace path to create the solution folder hierarchy since changing the solution output path should not change the created solution folders. And as you said we will naturally have less ".." in the hierarchy if we do so.

I will change it.

**Comment by ReMinoer** [comment]
Fixed with 64904a6 and released as 0.5.4.
Thanks again for the feedback !
